import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "HubTensor",
  description: "Generated by create next app",
  openGraph: {
    title: "HubTensor",
    description: ``,
    siteName: "",
    // url: new URL(`${process?.env?.REACT_APP_HOST}`),
  },

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
